sudo: required

services:
  - docker

cache:
  directories:
    - bundle

before_install:
  - npm install vnu-jar
  - sudo mkdir -m 777 build
  - ls bundle || sudo mkdir -m 777 bundle

script:
  - docker-compose run jekyll jekyll build
  - java -jar node_modules/vnu-jar/build/dist/vnu.jar --skip-non-html --errors-only --filterfile tests/config/vnufilter.txt build/
