sudo: required

services:
  - docker

before_install:
  - npm install vnu-jar

script:
  - docker-compose exec jekyll jekyll build
  - java -jar node_modules/vnu-jar/build/dist/vnu.jar --skip-non-html --errors-only --filterfile tests/config/vnufilter.txt build/
