sudo: required

services:
  - docker

cache:
  directories:
    - bundle

before_install:
  - npm install vnu-jar
  - sudo mkdir -m 777 build
  - ls bundle || sudo mkdir -m 777 bundle
  - sudo mkdir -m 777 app/.jekyll-cache

script:
  - ./scripts/run-tests.sh
