version: '2'
services:
  jekyll:
    build:
      context: .
      dockerfile: ./build-environment/Dockerfile
    image: rcremona/lil-website:0.3
    container_name: jekyll
    command: bash
    tty: true
    volumes:
        - ./app:/usr/src/lil-website/app
        - ./assets:/usr/src/lil-website/assets
        - ./builds:/usr/src/lil-website/builds
  apache:
    image: httpd
    container_name: apache
    ports:
        - "8081:80"
        # - "443:443"
    volumes:
        - ./builds/dev:/usr/local/apache2/htdocs/
        # - ./builds/prod:/usr/local/apache2/htdocs/
        - ./build-environment/apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
        - ./build-environment/apache/logs:/usr/local/apache2/logs

