version: 2.1
jobs:
  build:
    machine: true
    working_directory: ~/project
    steps:
      - checkout:
          path: ~/project

      - run:
          name: "Info"
          command: |
            docker-compose --version
            docker version
            npm --version

      - restore_cache:
          keys:
            - bundle-{{ checksum "app/Gemfile.lock" }}

      - run:
          name: "Setup"
          command: |
            npm install vnu-jar
            sudo mkdir -m 777 build
            ls bundle || sudo mkdir -m 777 bundle
            sudo mkdir -m 777 app/.jekyll-cache

      - run:
          name: "Test"
          command: |
            bash ./scripts/run_tests.sh

      - save_cache:
          key: bundle-{{ checksum "app/Gemfile.lock" }}
          paths:
            - ~/project/bundle/
